### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by nickquednow** [maverick-boiler-robotics-team-4272/2020PracticeBot#6]
because I do not have access to WPILib at home I am unsure if intakeSwitch is actually used anywhere. it is located in hopper.java, line 51. look in the master branch on the commit from 2/29/2020 to see what I am taking about

**Comment by Bobobalink** [comment]
I cannot find a variable called `intakeSwitch` anywhere. Additionally, `Hopper.java` line `51` is blank in the latest commit: https://github.com/maverick-boiler-robotics-team-4272/2020PracticeBot/blob/2eb1b7f384a05374a7793de872e5ff41a3943cb0/src/main/java/frc/robot/Hopper.java#L51
